/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as myTokenSol from './MyToken.sol/index.js';
export type { myTokenSol };
import type * as tokenCallerSol from './TokenCaller.sol/index.js';
export type { tokenCallerSol };
export * as factories from './factories/index.js';
export type { MyToken } from './MyToken.sol/MyToken.js';
export { MyToken__factory } from './factories/MyToken.sol/MyToken__factory.js';
export type { TokenCaller } from './TokenCaller.sol/TokenCaller.js';
export { TokenCaller__factory } from './factories/TokenCaller.sol/TokenCaller__factory.js';