/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as myTokenSol from './MyToken.sol/index.js';
export * as tokenCallerSol from './TokenCaller.sol/index.js';